import type { Site } from '@/types'

export const siteConfig: Site = {
	name: 'trishit.dev',
	title: 'Trishit Char | Full-Stack Developer, Programmer, Engineer',
	description:
		"Hi, I'm Trishit Char (Trishit) - A full stack developer with over two years of professional experience. I build web, mobile, desktop, server, and applied AI projects. Specializing in React, Next.js, TypeScript, Node.js, and AI integration. View my portfolio at trishit.dev to see projects like AI-flix and TcharGram. Available for freelance and full-time opportunities.",
	keywords: [
		'Trishit',
		'Trishit Char',
		'Trishit developer',
		'Trishit Char developer',
		'Trishit full stack developer',
		'Trishit Char portfolio',
		'Trishit portfolio',
		'trishit.dev',
		'Trishit.dev',
		'Trishit Char projects',
		'Trishit React developer',
		'Trishit TypeScript developer',
		'Trishit Next.js developer',
		'Trishit Node.js developer',
		'Trishit AI developer',
		'Trishit Char full stack',
		'Trishit MERN stack developer',
		'Trishit web developer',
		'Trishit Char React',
		'Trishit Char TypeScript',
		'Trishit software engineer',
		'Trishit Char software engineer',
		'Trishit programmer',
		'Trishit Char programmer',
		'Trishit full-stack',
		'Trishit Char AI projects',
		'trishitchar',
		'@trishitchar',
		'x.com/trishitchar',
		'twitter.com/trishitchar',
		'linkedin.com/in/trishitchar',
		'github.com/trishitchar',
		'instagram.com/trishit.char',
		'facebook.com/trishitchar',
		'Trishit Char India',
		'Trishit developer India',
		'Trishit Char West Bengal',
		'Trishit freelance developer',
		'hire Trishit Char',
		'hire Trishit',
		'Trishit Char contact',
		'Trishit contact',
		'AI-flix Trishit',
		'TcharGram Trishit',
		'Trishit Char AI-flix',
		'Trishit Char TcharGram',
	],
	siteUrl: 'https://trishit.dev',
	creator: { name: 'Trishit Char', url: 'https://trishit.dev' },
	ogImage: 'https://trishit.dev/opengraph-image.png',
	links: { 
		x: 'https://x.com/trishitchar', 
		github: 'https://github.com/trishitchar',
		linkedin: 'https://linkedin.com/in/trishitchar',
		twitter: 'https://twitter.com/trishitchar',
	},
}
