export const skillsConfig = [
  {
    category: 'Frontend',
    technologies: [
      'React',
      'Next.js',
      'TailwindCSS',
      'SCSS',
      'Headless UI',
      'ShadCN UI',
      'Framer motion',
      'GSAP',
      'Redux',
      'Recoil',
      'Zustand',
      'SWR',
      'Tanstack Query',
      'Tanstack Router',
      'React Hook Form',
      'Jest',
      'Vitest',
      'Cypress',
      'Playwright',
      'Storybook',
    ],
  },
  {
    category: 'Javascript runtime',
    technologies: [
      'Node.js',
      'Bun',
      'Deno',
      'Edge runtime (Vercel)',
      'CF Worker',
    ],
  },
  {
    category: 'Backend',
    technologies: [
      'Hono.js',
      'Express.js',
      'Fastapi',
      'Flask',
      'Go',
      'Fiber',
      'Mux',
    ],
  },
  {
    category: 'Mobile',
    technologies: ['React Native', 'Expo', 'Flutter'],
  },
  {
    category: 'Low Level',
    technologies: ['C', 'C++'],
  },
  {
    category: 'DevOps',
    technologies: ['Docker', 'Kubernetes', 'Terraform', 'AWS', 'GCP', 'Azure'],
  },
]
