export const skillsConfig = [
	{
		category: 'Frontend',
		technologies: [
			'React',
			'Next.js',
			'WordPress',
			'Chrome extension',
			'Redux',
			'Tanstack Query',
			'TailwindCSS',
			'SCSS',
			'ShadCN UI',
			'Framer Motion',
			'GSAP',
			'Zustand',
			'Tanstack Router',
			'React Hook Form',
			'Jest',
			'Vitest',
			'Playwright',
		],
	},
	{ category: 'Backend', technologies: [ 'Express.js', 'Hono.js', 'NestJS', 'Go',] },
	{ category: 'Mobile', technologies: ['React Native', 'Expo'] },
	{ category: 'Javascript runtime', technologies: ['Node.js', 'Bun', 'Deno', 'Edge runtime (Vercel)', 'CF Worker'] },
	{ category: 'DevOps', technologies: ['Docker', 'Kubernetes', 'Terraform', 'AWS', 'AWS EC2', 'AWS S3', 'GCP', 'Azure'] },
	{ category: 'Low Level', technologies: ['C', 'C++'] },
]
