import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiOutlineGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import { Link, animateScroll as scroll } from 'react-scroll';


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Trishit Char Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id="home" className="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
        <h1 className="font-burtons text-xl">T C</h1>
        <ul className="flex items-center space-x-4">
              <li>
                <Link to="skills" smooth={true} duration={500} className="hover:text-teal-500 text-1xl font-bold cursor-pointer">
                  Skills
                </Link>
              </li>
              <li>
                <Link to="education" smooth={true} duration={500} className="hover:text-teal-500 text-1xl font-bold cursor-pointer">
                  Education
                </Link>
              </li>
              <li>
                <Link to="projects" smooth={true} duration={500} className="hover:text-teal-500 text-1xl font-bold cursor-pointer">
                  Projects
                </Link>
              </li>
              <li>
                <a
                  href="https://github.com/trishitchar"
                  target="_blank"
                  rel="noreferrer"
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-500 text-white px-4 py-2 border-none rounded-md ml-4 hover:bg-teal-500"
                >
                  GitHub
                </a>
              </li>
              <li className="font-bold cursor-pointer transition duration-300 transform hover:scale-110">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className={`text-2xl ${darkMode ? 'text-white' : 'text-gray-800'} hover:text-teal-500`}
                />
              </li>
            </ul>
      </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Trishit Char
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer  ||  UI/UX Designer || Coder
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I am a motivated and versatile individual, always eager to take on new challenges. With a passion for learning I am dedicated to delivering high-quality results. With a positive attitude and a growth mindset, I am ready to make a meaningful contribution and achieve great things.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <button onClick={() => window.open("https://twitter.com/trishitchar", "_blank")}>
                <AiFillTwitterCircle />
              </button> 
              <button onClick={() => window.open("https://in.linkedin.com/in/trishit-char-5659b7200", "_blank")}>
                <AiFillLinkedin />
              </button> 
              <button onClick={() => window.open("https://github.com/trishitchar", "_blank")}>
                <AiOutlineGithub />
              </button> 
            </div>
            <div className="mx-auto flex flex-wrap bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} alt="Description of the image" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section id="skills" className="py-10">
          <div className=" font-bold">
            <h5 className="text-5xl py-1 dark:text-white ">Skills</h5>
            <div className="border-b dark:border-gray-300 border-gray-800 my-4"></div>
            <div className="flex justify-between ">
              <h1 className=" flex text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Language
              </h1>
              <div className="flex flex-row flex-wrap min-w-screen">
                <div className="text-2xl flex text-teal-500 px-4">C++</div>
                <div className="text-2xl flex text-purple-300 px-4">C</div>
                <div className="text-2xl flex text-teal-500 px-4">JAVA</div>
                <div className="text-2xl flex text-purple-300 px-4">JavaScript</div>
                <div className="text-2xl flex text-teal-500 px-4">HTML</div>
                <div className="text-2xl flex text-purple-300 px-4">CSS</div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="Description of the image" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Frontend
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Language I Use</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Tailwind CSS</p>
              <p className="text-gray-800 py-1">CSS 4</p>
              <p className="text-gray-800 py-1">Material UI</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="Description of the image" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Backend
              </h3>
              <p className="py-2">
                Backned technology generally I prefer
              </p>
              <h4 className="py-4 text-teal-600">Backend Tools I Use</h4>
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">MYSQL</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">Firebase</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} alt="Description of the image" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Others</h3>
              <p className="py-2">
                Other technology which I know or currently learning
              </p>
              <h4 className="py-4 text-teal-600">Other Tech I Use</h4>
              <p className="text-gray-800 py-1">GIT</p>
              <p className="text-gray-800 py-1">GitHub</p>
              <p className="text-gray-800 py-1">Postman</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section id="education" className="py-10">
          <div className=" font-bold">
            <h5 className="text-5xl py-1 dark:text-white ">Education</h5>
            <div className="border-b dark:border-gray-300 border-gray-800 my-4"></div>
            <div className="flex justify-between ">
              <h1 className=" flex text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Hooghly Engineering & Technology College
              </h1>
              <span className=" text-2xl flex text-teal-500"> 2021 - 2025 </span>
              <div>
                <div className=" text-2xl flex text-purple-300"> CGPA 8.74</div>
              </div> 
            </div>
            <div className="flex justify-between ">
              <h1 className=" flex text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Higher Secondary Exam  (WBCHSE)
              </h1>
              <span className=" text-2xl flex text-teal-500"> 2019 - 2021 </span>
              <div>
                <div className=" text-2xl flex text-purple-300"> 90% </div>
              </div> 
            </div>
            <div className="flex justify-between ">
              <h1 className=" flex text-3xl py-2 leading-8 text-gray-800 dark:text-gray-200">
              Madhyamik Pariksha (WBBSE)
              </h1>
              <span className=" text-2xl flex text-teal-500"> 2018 - 2019 </span>
              <div>
                <div className=" text-2xl flex text-purple-300"> 81% </div>
              </div> 
            </div>
          </div>
        </section>
        <section id="projects"  className="py-10">
          <div className=" font-bold">
            <h5 className="text-5xl py-1 dark:text-white ">Projects</h5>
            <div className="border-b dark:border-gray-300 border-gray-800 my-4"></div>
            <div className="flex justify-between ">
              <h1 className=" flex text-1xl py-1 leading-8 text-gray-800 dark:text-gray-200">
                I have Worked on a wide range of projects in frontend and Backend technology, Some of them are completed some of them are not.
              </h1>
            </div>
          </div>
        </section>
        <section>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/3 flex-1 relative">
            <Image
            className="rounded-lg object-top transition duration-300 ease-in-out transform hover:scale-110"
            width={"100%"}
            height={"100%"}
            layout="responsive"
            src={web1}
            />
            <div className="absolute cursor-pointer inset-0 flex flex-col items-center justify-center bg-black/50 opacity-0 hover:opacity-100 transition duration-300 ease-in-out">
              <p className="text-white text-center text-2xl px-4 py-2">Object detection using Next js and some tensorflow</p>
              <div className="flex space-x-4 mt-4">
                <a href='https://ai-powered-human-detection-tc.netlify.app/' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">Live Link</a>
                <a href='https://github.com/trishitchar/AI-powered-Human-detection' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">GitHub</a>
              </div>
            </div>
          </div>
          <div className="basis-1/3 flex-1 relative">
            <Image
            className="rounded-lg object-top transition duration-300 ease-in-out transform hover:scale-110"
            width={"100%"}
            height={"100%"}
            layout="responsive"
            src={web2}
            />
            <div className="absolute cursor-pointer inset-0 flex flex-col items-center justify-center bg-black/50 opacity-0 hover:opacity-100 transition duration-300 ease-in-out">
              <p className="text-white text-center text-2xl px-4 py-2">Custom telegram boy using python</p>
              <div className="flex space-x-4 mt-4">
                <a href='https://github.com/trishitchar/telegram-bots-trishitchar' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">Live Link</a>
                <a href='https://github.com/trishitchar/telegram-bots-trishitchar' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">GitHub</a>
              </div>
            </div>
          </div>
          <div className="basis-1/3 flex-1 relative">
            <Image
            className="rounded-lg object-top transition duration-300 ease-in-out transform hover:scale-110"
            width={"100%"}
            height={"100%"}
            layout="responsive"
            src={web3}
            />
            <div className="absolute cursor-pointer inset-0 flex flex-col items-center justify-center bg-black/70 opacity-0 hover:opacity-100 transition duration-300 ease-in-out">
              <p className="text-white text-center text-2xl px-4 py-2">This is a simple Java-based CLI chat application that allows clients to connect to a server and exchange messages in real-time.</p>
              <div className="flex space-x-4 mt-4">
                <a href='https://github.com/trishitchar/Chat_application_CLI' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">Live Link</a>
                <a href='https://github.com/trishitchar/Chat_application_CLI' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">GitHub</a>
              </div>
            </div>
          </div>
          <div className="basis-1/3 flex-1 relative">
            <Image
            className="rounded-lg object-top transition duration-300 ease-in-out transform hover:scale-110"
            width={"100%"}
            height={"100%"}
            layout="responsive"
            src={web4}
            />
            <div className="absolute cursor-pointer inset-0 flex flex-col items-center justify-center bg-black/50 opacity-0 hover:opacity-100 transition duration-300 ease-in-out">
              <p className="text-white text-center text-2xl px-4 py-2">Some Open Source contribution on famous project like hacktoberfest, AppWrite</p>
              <div className="flex space-x-4 mt-4">
                <a href='https://github.com/trishitchar' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">Live Link</a>
                <a href='https://github.com/trishitchar' target="_blank" rel="noreferrer" className="text-white hover:underline border-2 border-purple-400 bg-purple-400 rounded-md p-2">GitHub</a>
              </div>
            </div>
          </div>
          </div>
        </section>
      </main>
    </div>
  );
}
